version: '3'
services:
  # go_app:
  #   build: 
  #       context: ./go
  #       dockerfile: GoDockerfile
  #   ports:
  #     - "7075:7070"
  #   container_name: go_app_container  

  mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3300:3306
        volumes:
            - my-db:/var/lib/mysql
            - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf

volumes:
    my-db: